services:
  app:
    build: .
    container_name: desafio-tecnico-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:desafio_tecnico;DB_CLOSE_DELAY=-1
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_H2_CONSOLE_ENABLED: "true"